In [5]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [7]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
            'just loved it!',
            'will go again',
            'horrible food',
            'never go there',
            'poor service',
            'poor quality',
            'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [9]:
one_hot('amazing restaurant', 30)

[3, 11]

In [15]:
voc_size = 30
encoded_reviews = [one_hot(i, voc_size) for i in reviews]
encoded_reviews

[[17, 8],
 [3, 11],
 [12, 19],
 [12, 23, 9],
 [19, 9, 9],
 [1, 8],
 [27, 9, 4],
 [21, 20],
 [21, 27],
 [12, 9]]

In [17]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[17,  8,  0],
       [ 3, 11,  0],
       [12, 19,  0],
       [12, 23,  9],
       [19,  9,  9],
       [ 1,  8,  0],
       [27,  9,  4],
       [21, 20,  0],
       [21, 27,  0],
       [12,  9,  0]])

In [23]:
vector_size = 4
model = Sequential()
model.add(Embedding(voc_size, vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [25]:
X = padded_reviews
y = sentiment

In [27]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [29]:
model.fit(X, y, epochs = 50, verbose = 0 )

In [31]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.6076


[0.607585608959198, 1.0]

In [51]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 0.03679855,  0.00821853, -0.01074356,  0.04723307],
       [-0.0836292 ,  0.00334315,  0.06878307, -0.03048679],
       [-0.00169349, -0.01877086,  0.00892848, -0.03372469],
       [ 0.0942612 , -0.00255135, -0.00750796,  0.07500686],
       [ 0.07118826,  0.01292477,  0.00094277,  0.02087026],
       [ 0.03076627,  0.00204318, -0.04828128, -0.00729319],
       [-0.02662395,  0.01552855, -0.01269063, -0.04273832],
       [-0.04373714, -0.04116888,  0.04616351,  0.03775331],
       [ 0.01228758, -0.03713009,  0.0104102 ,  0.04312124],
       [-0.05583562, -0.08133569, -0.01344245, -0.04755702],
       [-0.01530745, -0.03033668, -0.02096367, -0.0093495 ],
       [ 0.08159832,  0.08276324, -0.013735  , -0.06426153],
       [-0.00415449, -0.01280261, -0.05930109,  0.05460554],
       [ 0.03309479,  0.02868462,  0.02666891,  0.03941942],
       [-0.04978148, -0.03405644,  0.00655032,  0.04827428],
       [ 0.03722758, -0.04836414,  0.04757092, -0.04909909],
       [ 0.01228759, -0.

In [45]:
weights[17]

array([ 0.08957838, -0.06691542, -0.03789336,  0.036252  ], dtype=float32)

In [47]:
weights[3]

array([ 0.0942612 , -0.00255135, -0.00750796,  0.07500686], dtype=float32)